# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::RSpec; end
module Wood::Node::Char::Objects; end
module Wood::Node::Int::Objects; end
module Wood::Parser::Token; end
