# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mutant` gem.
# Please instead update this file by running `bin/tapioca gem mutant`.

# source://mutant-0.11.14/lib/mutant/version.rb:3
module Mutant; end

# Current mutant version
#
# source://mutant-0.11.14/lib/mutant/version.rb:5
Mutant::VERSION = T.let(T.unsafe(nil), String)
