# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'byebug'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'sorbet-runtime'
gem 'tapioca'

gem 'mutant', path: '../../../mutant'
gem 'mutant-rspec'

gem 'wood-lexer', path: '../wood-lexer'
