# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'awesome_print'
gem 'factory_bot'
gem 'rspec'
gem 'rubocop-rspec'
gem 'simplecov', require: false
gem 'tapioca'
gem 'zeitwerk'
